import { programs } from '../data/programs';

export default function Registration({editing,form,errors,fileRef,previewUrl,existingCertificate,change,fileChange,removeSelectedFile,submit,validateInline,reset}){
  return <section id="registration" className="section"><h2>{editing?'Edit Trainee':'Pilot Trainee Registration'}</h2>
    <form className="form" onSubmit={submit} noValidate>
      {['name','email','phone'].map(n=><div className="field" key={n}><label>{n==='name'?'Full Name':n==='email'?'Email':'Phone Number'} <span className="required">*</span></label><input className={errors[n]?'invalid':''} name={n} type={n==='email'?'email':n==='phone'?'tel':'text'} value={form[n]} onChange={change} onBlur={()=>validateInline(n)} placeholder={n==='name'?'Enter trainee name':n==='email'?'Enter email':'Enter 10-digit phone number'} />{errors[n]&&<small className="error">{errors[n]}</small>}</div>)}
      <div className="field"><label>Training Program <span className="required">*</span></label><select className={errors.program?'invalid':''} name="program" value={form.program} onChange={change} onBlur={()=>validateInline('program')}><option value="">Select Program</option>{programs.map(p=><option key={p.title}>{p.title}</option>)}</select>{errors.program&&<small className="error">{errors.program}</small>}</div>
      <div className="field"><label>Experience Level <span className="required">*</span></label><select className={errors.experience?'invalid':''} name="experience" value={form.experience} onChange={change} onBlur={()=>validateInline('experience')}><option value="">Select Experience Level</option><option>Beginner</option><option>Intermediate</option><option>Advanced</option></select>{errors.experience&&<small className="error">{errors.experience}</small>}</div>
      <div className="field"><label>Upload Medical Certificate <span className="required">*</span></label><input ref={fileRef} id="medicalCertificate" className={errors.medicalCertificate?'invalid':''} type="file" name="medicalCertificate" accept=".pdf,.jpg,.jpeg,.png,application/pdf,image/jpeg,image/png" onChange={fileChange}/><small className="hint">PDF, JPG, JPEG or PNG • Maximum 5 MB{editing?' • Leave empty to keep the existing certificate':''}</small>
        {form.medicalCertificate&&<div className="fileActions"><small className="fileName">Selected: {form.medicalCertificate.name}</small><a className="fileBtn" href={previewUrl} target="_blank" rel="noreferrer">View</a><button className="fileBtn removeFile" type="button" onClick={removeSelectedFile}>Remove</button></div>}
        {!form.medicalCertificate&&editing&&existingCertificate?.originalName&&<div className="fileActions"><small className="fileName">Current: {existingCertificate.originalName}</small><a className="fileBtn" href={`/api/trainees/${editing}/medical-certificate`} target="_blank" rel="noreferrer">View</a></div>}
        {errors.medicalCertificate&&<small className="error">{errors.medicalCertificate}</small>}</div>
      <div className="field full"><label>Address <span className="required">*</span></label><textarea className={errors.address?'invalid':''} name="address" value={form.address} onChange={change} onBlur={()=>validateInline('address')} rows="3" placeholder="Enter address" />{errors.address&&<small className="error">{errors.address}</small>}</div>
      <div className="actions full"><button className="btn" type="submit">{editing?'Update Trainee':'Add Trainee'}</button><button className="btn secondary" type="button" onClick={reset}>Clear</button></div>
    </form>
  </section>;
}
